# Generated by Django 4.2.6 on 2023-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='artical_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
