# Generated by Django 4.2.6 on 2023-11-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
