# Generated by Django 4.2.6 on 2023-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='artical_pic'),
        ),
    ]
