# Generated by Django 4.2.6 on 2023-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_artical_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='category',
            field=models.CharField(choices=[('programming', 'programming'), ('medicine', 'medicine'), ('computer', 'computer'), ('phones', 'phones'), ('cooking', 'cooking')], default='cooking', max_length=30),
        ),
        migrations.AlterField(
            model_name='artical',
            name='artical_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
