# Generated by Django 4.2.6 on 2023-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_artical_category_alter_artical_artical_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.ImageField(upload_to='artical_pic'),
        ),
    ]
