# Generated by Django 4.2.6 on 2023-11-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
